from aiogram.utils.callback_data import CallbackData

project_call = CallbackData("project", "name", "id")
department_call = CallbackData("department", "name", "id")
user_call = CallbackData("user", "id")
pinned_project_call = CallbackData('pinnedProject', 'name', 'id')
edit_project = CallbackData('editProject', 'id', 'name')
delete_project = CallbackData('deleteProject', 'id')
worker_call = CallbackData('worker', 'id', 'name')
add_worker_call = CallbackData('addWorker', 'deprtment_id')
add_user_to_department = CallbackData('addUserToDepartment', 'id')
unzip = CallbackData('unzip', 'id', 'name')
archive = CallbackData('archive', 'id', 'name')
history_pays = CallbackData('historyPays', 'id')
add_pay = CallbackData('addPay', 'id')
accept_request_pay = CallbackData('accept_request', 'pay_id')
not_approved_pay = CallbackData('not_approved_pay', 'pay_id')
anchor_callback = CallbackData('anchor', 'id_project', 'id_user')
add_admin_to_department = CallbackData('admin', 'id_department', 'id_user', 'id_project')
adds_user_to_department = CallbackData('user_add', 'id_department', 'id_user', 'id_project')
edit_department = CallbackData('edit_dep', 'id_department')
set_status_department = CallbackData('status_department', 'id_department', 'status')
remove_admin_from_department = CallbackData('remove_admin', 'id_department', 'id_user', 'id_project')
accept_request_pay_admin = CallbackData('accept_request_admin', 'pay_id')
not_approved_pay_admin = CallbackData('not_approved_pay_admin', 'pay_id')
